# Versi API yg didefinisikan
apiVersion: apps/v1
# Jenis Objek Kubernetes
kind: StatefulSet
# Meta data untuk StatefulSet
metadata: 
  # Nama StatefulSet
  name: mongodb
# Spesifikasi untuk StatefulSet
spec:
  # Nama service yang digunakan oleh StatefulSet
  serviceName: mongo-service
  # Jumlah replika pod yang akan dibuat
  replicas: 1
    # Selektor untuk memilih pod
  selector:
    # Pod yang dipilih harus sesuai ketentuan
    matchLabels:
      app: database
      selector: mongodb
  # Template untuk membuat pod
  template:
    metadata:
      # Label pod
      labels:
        app: database
        selector: mongodb
    # Spesifikasi untuk pod 
    spec:
      # Konfigurasi container untuk pod
      containers:
      # Nama Container
      - name: mongodb
      # Nama image yang digunakan untuk membuat container
        image: mongo:4.4.25
        # Port yang digunakan
        ports:
        # Port yang digunakan untuk mengakses container
        - containerPort: 27017
        # Environment variables yang dibutuhkan oleh aplikasi
        env:
        # Nama environment variable
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
        # Nilai environment variable
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: etc/mongo-credentials/MONGO_ROOT_PASSWORD
        # volume mount yang dieksekusi oleh aplikasi
        volumeMounts:
        # volume mount dan path yang didalam container yang akan digunakan untuk PersistentVolume
        - name: mongo-data
          mountPath: /data/db
        - name: mongo-config
          mountPath: /config
        - name: mongo-credentials
          mountPath: /etc/mongo-credentials
      # Volume yang didefinisikan pada aplikasi
      volumes:
      - name : mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc
      - name: mongo-config
        configMap:
          # Nama ConfigMap yang akan digunakan
          name: mongo-config
          items:
          - key: mongo.conf
            path: mongo.conf
      # Nama Screet yang akan digunakan
      - name: mongo-credentials
        secret:
          secretName: mongo-credentials
          items:
          # key dan path pada secret yang akan digunakan
          - key: MONGO_ROOT_USERNAME
            path: MONGO_ROOT_USERNAME
          - key: MONGO_ROOT_PASSWORD
            path: MONGO_ROOT_PASSWORD
