# Versi API yg didefinisikan
apiVersion: v1
# Jenis Objek Kubernetes
kind: Secret
# Meta data untuk Secret
metadata:
  name: mongo-credentials
# Tipe data yang akan disimpan dalam Secret
type: Opaque
# Data yang akan disimpan dalam Secret
data:
  # Data dengan key
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==